"""The tool reference page, generated from the running server (#28).

    python -m simba_mcp.reference            # write docs/tools.md
    python -m simba_mcp.reference --check    # exit 1 when the committed page differs

Every tool the server registers — name, title, whether it reads or writes, its description and its
parameters — rendered from the same objects `tools/list` serves, so the page cannot drift from the
server. It states the tool count and no version, so a release does not change it.
"""

from __future__ import annotations

import argparse
import inspect
import json
import sys
from pathlib import Path
from typing import Any

import anyio

DOCS = Path(__file__).resolve().parents[2] / "docs" / "tools.md"

# Section order and headings, by the module that defines each tool.
SECTIONS = {
    "guidance": "Workflow guidance",
    "data": "Data and pipelines",
    "projects": "Projects",
    "models": "Models",
    "results": "Results",
    "scenarios": "Scenarios and optimization",
    "studies": "Studies",
    "recipes": "Study recipes",
    "drafts": "Recipe drafts",
    "quality": "Quality policies, evaluation and decisions",
}


def _type(schema: dict[str, Any]) -> str:
    """A short, readable type for one JSON-schema property."""
    if "anyOf" in schema:
        parts = [_type(s) for s in schema["anyOf"] if s.get("type") != "null"]
        nullable = any(s.get("type") == "null" for s in schema["anyOf"])
        return " \\| ".join(parts) + (" (optional)" if nullable else "")
    kind = schema.get("type")
    if kind == "array":
        return f"list of {_type(schema.get('items', {}))}"
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "enum" in schema:
        return " \\| ".join(json.dumps(v) for v in schema["enum"])
    return kind or "any"


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ").strip()


def _effect(tool: Any) -> str:
    hints = tool.annotations
    if hints is None:
        return "unspecified"
    if hints.read_only_hint:
        return "reads"
    return "writes, destructive" if hints.destructive_hint else "writes"


def render(tools: list[Any], sections: dict[str, str], compact_mode: bool = False) -> str:
    """The Markdown page for ``tools``; ``sections`` maps a tool name to its section key."""
    by_section: dict[str, list[Any]] = {key: [] for key in SECTIONS}
    for tool in sorted(tools, key=lambda t: t.name):
        by_section.setdefault(sections.get(tool.name, "other"), []).append(tool)
    out = [
        "# Tools",
        "",
        "<!-- Generated by `python -m simba_mcp.reference` from the running server. Do not edit by hand. -->",
        "",
        (
            f"The server registers **{len(tools)} tools**. Each entry is what `tools/list` returns: the "
            "tool's name, whether it reads or writes, its description and its parameters. Effects are MCP "
            "annotations — hints for clients, never authorization."
        ),
        "",
    ]
    for key, members in by_section.items():
        if not members:
            continue
        heading = SECTIONS.get(key, key.title())
        out.append(f"- [{heading}](#{_anchor(heading)}) ({len(members)})")
    out.append("")
    for key, members in by_section.items():
        if not members:
            continue
        out += [f"## {SECTIONS.get(key, key.title())}", ""]
        for tool in members:
            out += [f"### `{tool.name}`", ""]
            if compact_mode:
                out += [f"[Full tool contract](tools.md#{tool.name})", ""]
            meta = [f"**{_effect(tool)}**"]
            if tool.title:
                meta.insert(0, tool.title)
            out += [" · ".join(meta), ""]
            description = inspect.cleandoc(tool.description or "")
            if description:
                out += [description, ""]
            props = (tool.input_schema or {}).get("properties", {})
            required = set((tool.input_schema or {}).get("required", []))
            if props:
                out += ["| Parameter | Type | Required | Default |", "|---|---|---|---|"]
                for name, schema in props.items():
                    default = (
                        "" if "default" not in schema else f"`{json.dumps(schema['default'])}`"
                    )
                    out.append(
                        f"| `{name}` | {_cell(_type(schema))} | {'yes' if name in required else ''} | "
                        f"{default} |"
                    )
                out.append("")
            else:
                out += ["No parameters.", ""]
    return "\n".join(out).rstrip("\n") + "\n"


def _anchor(heading: str) -> str:
    return "".join(c for c in heading.lower().replace(" ", "-") if c.isalnum() or c == "-")


def current(description_mode: str = "legacy") -> str:
    """The page for the tools this server registers right now."""
    from simba_mcp.server import TOOLS, create_server

    tools = anyio.run(create_server(description_mode).list_tools)
    sections = {fn.__name__: fn.__module__.rsplit(".", 1)[-1] for fn in TOOLS}
    return render(tools, sections, compact_mode=description_mode == "compact")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate docs/tools.md from the running server.")
    parser.add_argument(
        "--check", action="store_true", help="exit 1 when docs/tools.md is out of date"
    )
    args = parser.parse_args(argv)
    from simba_mcp.catalogue import COMPACT
    from simba_mcp.guidance import CONTENT, MANIFEST
    from simba_mcp.server import TOOLS

    outputs = {DOCS: current(), DOCS.with_name("tools-compact.md"): current("compact")}
    for tool in TOOLS:
        entry = COMPACT.get(tool.__name__)
        if entry:
            relative = MANIFEST["topics"][entry.topic]["sections"]["tool-reference"]
            outputs[Path(str(CONTENT.joinpath(relative)))] = (
                f"# {tool.__name__}: full contract\n\n"
                "<!-- Generated from the handler docstring by simba_mcp.reference. -->\n\n"
                + inspect.getdoc(tool)
                + "\n"
            )
    stale = []
    for path, page in outputs.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != page:
                stale.append(str(path))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(page, encoding="utf-8", newline="\n")
    if stale:
        print("Generated references are stale: " + ", ".join(stale), file=sys.stderr)
        return 1
    print(
        "Generated references are current"
        if args.check
        else "Wrote full, compact and packaged references"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
