"""Explicit workflow coverage decisions and generated current-role documentation.

This is maintenance tooling, not runtime registration. Profiles remain canonical.
"""

import argparse
import json
import posixpath
import re
from pathlib import Path

import anyio
from jsonschema import Draft202012Validator

from . import CONTENT, MANIFEST

ROOT = Path(__file__).resolve().parents[3]
DECISIONS = json.loads(CONTENT.joinpath("coverage.json").read_text(encoding="utf-8"))
START = "<!-- current-role-coverage:start -->"
END = "<!-- current-role-coverage:end -->"


def validate_coverage(tools, profiles, decisions, workflows):
    """Fail on unreviewed catalogue changes and unavailable example dependencies."""
    known = {tool.name: tool for tool in tools}
    classified = []
    examples = {workflow.case.id: workflow for workflow in workflows}
    for family in decisions:
        assert family["reason"].strip(), f"Missing role rationale: {family['family']}"
        assert family["examples"] or family.get("example_limitation", "").strip(), (
            f"Missing example decision: {family['family']}"
        )
        assert family["guidance"] or family.get("guidance_limitation", "").strip(), (
            f"Missing guidance decision: {family['family']}"
        )
        for topic in family["guidance"]:
            assert topic in MANIFEST["topics"], f"Unknown guidance topic: {topic}"
        for example in family["examples"]:
            assert example in examples, f"Unknown workflow example: {example}"
        for name in family["tools"]:
            assert name in known, f"Coverage references removed tool: {name}"
            classified.append(name)
            for role, members in profiles.items():
                assert (name in members) == (role in family["roles"]), (
                    f"Role decision differs from {role} membership: {name}"
                )
    assert len(classified) == len(set(classified)), "Duplicate tool coverage decisions"
    assert set(classified) == set(known), (
        f"Unclassified registered tools: {sorted(set(known) - set(classified))}"
    )
    for workflow in workflows:
        entry = MANIFEST["topics"][workflow.topic]
        assert workflow.section in entry["sections"], (
            f"Missing workflow guidance: {workflow.case.id}"
        )
        for step in workflow.case.steps:
            assert step.tool in known, f"Unknown example tool: {step.tool}"
            Draft202012Validator(known[step.tool].input_schema).validate(step.arguments)
            for role in workflow.roles:
                assert role in ("full", "data_scientist") or step.tool in profiles[role], (
                    f"Example {workflow.case.id} requires {step.tool} excluded from {role}"
                )


def validate_links(content, paths, source="SKILL.md"):
    """Check all local reference links in a standalone exported Skill."""
    for relative in re.findall(r"\]\(([^)#]+)(?:#[^)]*)?\)", content):
        if ":" in relative or relative.startswith("#"):
            continue
        target = posixpath.normpath(posixpath.join(posixpath.dirname(source), relative))
        assert target in paths, f"Broken guidance link: {source} -> {relative}"


def render_counts(tools, profiles):
    jobs = {
        "marketer": "Actual-data/campaign reporting, saved evidence, comparisons, authorised plans and run curation",
        "reviewer": "Scientific evidence/provenance, assessments, declarations and evidence-bound recommendations",
    }
    rows = [
        START,
        "",
        "| Profile | Current tools | Intended work |",
        "| --- | ---: | --- |",
        f"| `full` | {len(tools)} | Mixed jobs and explicit fallback |",
        f"| `data_scientist` | {len(tools)} | All data, modelling, Studies, review and planning work |",
    ]
    rows.extend(
        f"| `{role}` | {len(members)} | {jobs[role]} |" for role, members in profiles.items()
    )
    return "\n".join([*rows, "", END])


def replace_counts(document, tools, profiles):
    assert START in document and END in document, "Missing generated role-count markers"
    before, remainder = document.split(START, 1)
    _, after = remainder.split(END, 1)
    return before + render_counts(tools, profiles) + after


def render_decisions(decisions):
    out = [
        "# Role coverage decisions",
        "",
        "<!-- Generated by python -m simba_mcp.guidance.coverage. -->",
        "",
        (
            "Every registered tool has an explicit decision below. Full/data_scientist include all tools. "
            "Profiles select startup catalogues and confer no permissions. Intentional exclusions "
            "are valid; use a separate full connection for authoring or cross-role work."
        ),
        "",
        "| Family and exact tools | Marketer | Reviewer | Decision and guidance |",
        "| --- | --- | --- | --- |",
    ]
    for family in decisions:
        names = ", ".join(f"`{name}`" for name in family["tools"])
        topics = ", ".join(family["guidance"]) or family["guidance_limitation"]
        out.append(
            f"| {family['family']}: {names} | "
            f"{'included' if 'marketer' in family['roles'] else 'excluded'} | "
            f"{'included' if 'reviewer' in family['roles'] else 'excluded'} | "
            f"{family['reason']} Guidance: {topics}. |"
        )
    out += ["", "## Example scope", ""]
    for family in decisions:
        detail = ", ".join(family["examples"]) or family["example_limitation"]
        out.append(f"- {family['family']}: {detail}")
    return "\n".join(out) + "\n"


def render_examples(workflows):
    """Publish exact calls and evidence from existing executable fixture contracts."""
    out = [
        "# Executable synthetic examples",
        "",
        "<!-- Generated from evaluation.role_workflows by guidance.coverage. -->",
        "",
        (
            "These examples execute through registered selected profiles with HTTPX MockTransport. "
            "Identifiers and outputs are synthetic, not live acceptance. Follow the declared prerequisites "
            "before using real objects. Refusals and uncertain writes never authorise a retry."
        ),
        "",
    ]
    for workflow in workflows:
        out += [
            f"## {workflow.case.id}",
            "",
            workflow.intent,
            "",
            f"Profiles: {', '.join(workflow.roles)}.",
            "",
            f"Prerequisites: {workflow.preconditions}",
            "",
            f"Interpretation and recovery: {workflow.limits}",
            "",
        ]
        for index, step in enumerate(workflow.case.steps, 1):
            call = {"name": step.tool, "arguments": step.arguments}
            out += [
                f"Step {index}:",
                "",
                "```json",
                json.dumps(call, indent=2),
                "```",
                "",
                "Expected observable fields:",
                "",
                "```json",
                json.dumps(step.expected, indent=2),
                "```",
                "",
            ]
    return "\n".join(out)


def generated_outputs(tools, profiles, decisions, workflows):
    outputs = {ROOT / "docs/role-coverage.md": render_decisions(decisions)}
    document = ROOT / "docs/tool-profiles.md"
    outputs[document] = replace_counts(document.read_text(encoding="utf-8"), tools, profiles)
    groups = {}
    for workflow in workflows:
        groups.setdefault((workflow.topic, workflow.section), []).append(workflow)
    for (topic, section), members in groups.items():
        relative = MANIFEST["topics"][topic]["sections"][section + "-examples"]
        outputs[Path(str(CONTENT.joinpath(relative)))] = render_examples(members)
    return outputs


def main():
    from simba_mcp.evaluation.role_workflows import role_workflows
    from simba_mcp.profiles import PROFILES
    from simba_mcp.server import create_server

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    tools = anyio.run(create_server().list_tools)
    workflows = role_workflows()
    validate_coverage(tools, PROFILES, DECISIONS, workflows)
    stale = []
    for path, content in generated_outputs(tools, PROFILES, DECISIONS, workflows).items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        parser.exit(1, "Stale role documentation/examples: " + ", ".join(stale) + "\n")
    print("Role coverage, current counts and executable examples are current.")


if __name__ == "__main__":
    main()
